from __future__ import annotations

import hmac as _hmac
import time
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Optional

from ..types.challenge import ChallengeRequest
from ..types.config import PineLabsOnlineServerConfig
from ..types.credential import Credential, CredentialChallenge, CredentialPayload, VerificationResult
from ..types.payment import PaymentGateway, PaymentMethod
from ..utils.base64url import decode_json, encode_json, is_base64_url
from ..utils.hmac_sig import compute_challenge_id, derive_challenge_hmac_key
from ..utils.validation import validate_config

PAYMENT_HEADER_PREFIX = "Payment "


class CredentialVerifier:
    """Verifies client Payment credentials against the derived server challenge key."""

    def __init__(self, config: PineLabsOnlineServerConfig) -> None:
        validate_config(config)
        self._secret_key = derive_challenge_hmac_key(config.clientSecret)
        self._realm = config.realm or config.env
        self._available_payment_methods = list(config.availablePaymentMethods)

    def verify(self, credential_header: Optional[str]) -> VerificationResult:
        """Decode and validate a `P3P-Credential: Payment <payload>` header."""
        encoded = self._extract_payload(credential_header or "")
        if not encoded:
            return VerificationResult(
                valid=False,
                error="Invalid P3P-Credential header format. Expected: Payment <base64url>",
            )

        try:
            raw = decode_json(encoded)
        except Exception:
            return VerificationResult(
                valid=False, error="Failed to decode credential from P3P-Credential header"
            )

        try:
            credential = _dict_to_credential(raw)
        except Exception:
            return VerificationResult(
                valid=False, error="Credential contains an incomplete challenge"
            )

        challenge = credential.challenge
        if not challenge.id or not challenge.realm or challenge.request is None:
            return VerificationResult(
                valid=False, credential=credential, error="Credential contains an incomplete challenge"
            )

        if challenge.realm != self._realm:
            return VerificationResult(
                valid=False,
                credential=credential,
                error=f'Challenge realm mismatch. Expected "{self._realm}", got "{challenge.realm}"',
            )

        if not challenge.request.availablePaymentMethods:
            return VerificationResult(
                valid=False,
                credential=credential,
                error="Challenge missing available payment methods",
            )

        try:
            expires_ms = _iso_to_epoch_ms(challenge.expires)
        except Exception:
            return VerificationResult(valid=False, credential=credential, error="Challenge has expired")
        if expires_ms <= time.time() * 1000:
            return VerificationResult(valid=False, credential=credential, error="Challenge has expired")

        request_dict: Dict[str, Any] = {
            "scheme": challenge.request.scheme,
            "amount": challenge.request.amount,
            "currency": challenge.request.currency,
            "resource": challenge.request.resource,
            "availablePaymentMethods": _payment_method_values(challenge.request.availablePaymentMethods),
        }
        request_base64 = encode_json(request_dict)
        expected_id = compute_challenge_id(
            self._secret_key,
            challenge.realm,
            challenge.intent,
            request_base64,
            challenge.expires,
        )

        if not _hmac.compare_digest(
            challenge.id.encode() if isinstance(challenge.id, str) else challenge.id,
            expected_id.encode() if isinstance(expected_id, str) else expected_id,
        ):
            return VerificationResult(
                valid=False,
                credential=credential,
                error="Challenge HMAC verification failed. The challenge was not generated by this server.",
            )

        if not credential.payload or not credential.payload.token:
            return VerificationResult(
                valid=False, credential=credential, error="Credential missing payment token"
            )

        if not credential.payload.payment_method:
            return VerificationResult(
                valid=False, credential=credential, error="Credential missing selected payment method"
            )

        selected_payment_method = _payment_method_value(credential.payload.payment_method)
        challenge_methods = _payment_method_values(challenge.request.availablePaymentMethods)
        server_methods = _payment_method_values(self._available_payment_methods)
        if selected_payment_method not in challenge_methods or selected_payment_method not in server_methods:
            return VerificationResult(
                valid=False,
                credential=credential,
                error=f"Selected payment method {selected_payment_method} is not accepted by this server challenge",
            )

        return VerificationResult(valid=True, credential=credential)

    @staticmethod
    def _extract_payload(header: str) -> Optional[str]:
        trimmed = header.strip()
        if trimmed.startswith(PAYMENT_HEADER_PREFIX):
            payload = trimmed[len(PAYMENT_HEADER_PREFIX):].strip()
            return payload if is_base64_url(payload) else None
        return None


def _dict_to_credential(raw: Dict[str, Any]) -> Credential:
    ch = raw.get("challenge") or {}
    req = ch.get("request") or {}
    payload = raw.get("payload") or {}
    return Credential(
        challenge=CredentialChallenge(
            id=ch.get("id", ""),
            realm=ch.get("realm", ""),
            paymentGateway=_parse_payment_gateway(ch.get("paymentGateway", ch.get("payment_gateway"))),
            intent=ch.get("intent", ""),
            request=ChallengeRequest(
                scheme=req.get("scheme", ""),
                amount=str(req.get("amount", "")),
                currency=req.get("currency", ""),
                resource=req.get("resource", ""),
                availablePaymentMethods=_parse_payment_methods(
                    req.get("availablePaymentMethods", req.get("available_payment_methods"))
                ),
            ),
            expires=ch.get("expires", ""),
        ),
        source=raw.get("source", ""),
        payload=CredentialPayload(
            type=payload.get("type", "token"),
            token=payload.get("token", ""),
            payment_method=_parse_payment_method(payload.get("payment_method", payload.get("paymentMethod"))),
            payment_method_reference_id=payload.get("payment_method_reference_id") or payload.get("paymentMethodReferenceId"),
            mobile_number=payload.get("mobile_number") or payload.get("mobileNumber"),
        ),
    )


def _iso_to_epoch_ms(iso: str) -> float:
    if iso.endswith("Z"):
        iso = iso[:-1] + "+00:00"
    dt = datetime.fromisoformat(iso)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.timestamp() * 1000


def _parse_payment_gateway(value: Any) -> Optional[PaymentGateway]:
    if value is None:
        return None
    return PaymentGateway.PineLabsOnline if value == PaymentGateway.PineLabsOnline.value else value


def _parse_payment_method(value: Any) -> PaymentMethod:
    if value == PaymentMethod.RESERVE_PAY.value:
        return PaymentMethod.RESERVE_PAY
    if value == PaymentMethod.OTM.value:
        return PaymentMethod.OTM
    if value == PaymentMethod.CARD.value:
        return PaymentMethod.CARD
    if value == PaymentMethod.CREDIT_EMI.value:
        return PaymentMethod.CREDIT_EMI
    if value == PaymentMethod.Crypto.value:
        return PaymentMethod.Crypto
    return value or ""


def _parse_payment_methods(value: Any) -> List[PaymentMethod]:
    if not isinstance(value, list):
        return []
    return [_parse_payment_method(item) for item in value]


def _payment_method_value(value: Any) -> str:
    return value.value if isinstance(value, PaymentMethod) else str(value or "")


def _payment_method_values(values: Iterable[Any]) -> List[str]:
    return [_payment_method_value(value) for value in values]
