from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from ..config.environments import DEFAULT_REALM
from ..types.challenge import ChallengeRequest
from ..types.config import PluralSellerConfig
from ..types.credential import Credential, CredentialChallenge, CredentialPayload, VerificationResult
from ..utils.base64url import decode_json, encode_json
from ..utils.hmac_sig import compute_challenge_id

PAYMENT_HEADER_PREFIX = "Payment "


class CredentialVerifier:
    """Verifies buyer Payment credentials against the seller challenge secret."""

    def __init__(self, config: PluralSellerConfig) -> None:
        self._secret_key = config.challengeSecretKey
        self._realm = config.realm or DEFAULT_REALM

    def verify(self, authorization_header: Optional[str]) -> VerificationResult:
        """Decode and validate an `Authorization: Payment <payload>` header."""
        encoded = self._extract_payload(authorization_header or "")
        if not encoded:
            return VerificationResult(
                valid=False,
                error="Invalid Authorization header format. Expected: Payment <base64url>",
            )

        try:
            raw = decode_json(encoded)
        except Exception:
            return VerificationResult(
                valid=False, error="Failed to decode credential from Authorization header"
            )

        try:
            credential = _dict_to_credential(raw)
        except Exception:
            return VerificationResult(
                valid=False, error="Credential contains an incomplete challenge"
            )

        challenge = credential.challenge
        if not challenge.id or not challenge.realm or not challenge.method or challenge.request is None:
            return VerificationResult(
                valid=False, credential=credential, error="Credential contains an incomplete challenge"
            )

        if challenge.realm != self._realm:
            return VerificationResult(
                valid=False,
                credential=credential,
                error=f'Challenge realm mismatch. Expected "{self._realm}", got "{challenge.realm}"',
            )

        if challenge.method != "plural":
            return VerificationResult(
                valid=False,
                credential=credential,
                error=f"Unsupported payment method: {challenge.method}",
            )

        try:
            expires_ms = _iso_to_epoch_ms(challenge.expires)
        except Exception:
            return VerificationResult(valid=False, credential=credential, error="Challenge has expired")
        if expires_ms <= time.time() * 1000:
            return VerificationResult(valid=False, credential=credential, error="Challenge has expired")

        request_dict: Dict[str, Any] = {
            "scheme": challenge.request.scheme,
            "amount": challenge.request.amount,
            "currency": challenge.request.currency,
            "resource": challenge.request.resource,
        }
        request_base64 = encode_json(request_dict)
        expected_id = compute_challenge_id(
            self._secret_key,
            challenge.realm,
            challenge.method,
            challenge.intent,
            request_base64,
            challenge.expires,
        )

        if challenge.id != expected_id:
            return VerificationResult(
                valid=False,
                credential=credential,
                error="Challenge HMAC verification failed. The challenge was not generated by this server.",
            )

        if not credential.payload or not credential.payload.token:
            return VerificationResult(
                valid=False, credential=credential, error="Credential missing payment token"
            )

        return VerificationResult(valid=True, credential=credential)

    @staticmethod
    def _extract_payload(header: str) -> Optional[str]:
        trimmed = header.strip()
        if trimmed.startswith(PAYMENT_HEADER_PREFIX):
            return trimmed[len(PAYMENT_HEADER_PREFIX):].strip() or None
        return None


def _dict_to_credential(raw: Dict[str, Any]) -> Credential:
    ch = raw.get("challenge") or {}
    req = ch.get("request") or {}
    payload = raw.get("payload") or {}
    return Credential(
        challenge=CredentialChallenge(
            id=ch.get("id", ""),
            realm=ch.get("realm", ""),
            method=ch.get("method", ""),
            intent=ch.get("intent", ""),
            request=ChallengeRequest(
                scheme=req.get("scheme", ""),
                amount=str(req.get("amount", "")),
                currency=req.get("currency", ""),
                resource=req.get("resource", ""),
            ),
            expires=ch.get("expires", ""),
        ),
        source=raw.get("source", ""),
        payload=CredentialPayload(
            type=payload.get("type", "token"),
            token=payload.get("token", ""),
            customer_reference=payload.get("customer_reference") or payload.get("customerReference"),
        ),
    )


def _iso_to_epoch_ms(iso: str) -> float:
    if iso.endswith("Z"):
        iso = iso[:-1] + "+00:00"
    dt = datetime.fromisoformat(iso)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.timestamp() * 1000
