from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional


class MppErrorCode(str, Enum):
    VALIDATION_FAILED = "MPP_VALIDATION_FAILED"
    AUTHENTICATION_FAILED = "MPP_AUTHENTICATION_FAILED"
    AGENT_NOT_AUTHORIZED = "MPP_AGENT_NOT_AUTHORIZED"
    AGENT_ALREADY_EXISTS = "MPP_AGENT_ALREADY_EXISTS"
    MANDATE_NOT_FOUND = "MPP_MANDATE_NOT_FOUND"
    MANDATE_NOT_AUTHORIZED = "MPP_MANDATE_NOT_AUTHORIZED"
    MANDATE_EXPIRED = "MPP_MANDATE_EXPIRED"
    CUSTOMER_NOT_FOUND = "MPP_CUSTOMER_NOT_FOUND"
    CUSTOMER_MANDATE_MISMATCH = "MPP_CUSTOMER_MANDATE_MISMATCH"
    TOKEN_NOT_FOUND = "MPP_TOKEN_NOT_FOUND"
    TOKEN_EXPIRED = "MPP_TOKEN_EXPIRED"
    TOKEN_REVOKED = "MPP_TOKEN_REVOKED"
    INSUFFICIENT_AVAILABLE_BALANCE = "MPP_INSUFFICIENT_AVAILABLE_BALANCE"
    AMOUNT_EXCEEDS_LIMIT = "MPP_AMOUNT_EXCEEDS_LIMIT"
    CHARGES_EXHAUSTED = "MPP_CHARGES_EXHAUSTED"
    DUPLICATE_REQUEST = "MPP_DUPLICATE_REQUEST"
    UPI_GATEWAY_ERROR = "MPP_UPI_GATEWAY_ERROR"
    INTERNAL_ERROR = "MPP_INTERNAL_ERROR"


@dataclass
class MppErrorDetails:
    source: str
    step: str
    reason: str
    field: Optional[str] = None


@dataclass
class MppErrorResponse:
    error: Dict[str, Any] = field(default_factory=dict)
